### ISSUE TITLE
"no window" option by default lead to some crash

### ISSUE THREAD

**Issue by ghost** [nesnes/teleplot-vscode#1]
Hi !

First, thank you for your incredible work on this extension !! 

I use this on some old PC at my school. The fact that there is "no window" by default selected lead to crash or slow down very quicly our computers due to the amount of datas displayed at the same time. 

To avoid that, can we have an other default option selected, or a parameters to change that value by default ? 

Thanks a lot 👍

**Comment by IamPhytan** [comment]
Didn't had this problem for my part with UDP packets

**Comment by nesnes** [comment]
I’m a bit late reading this, but thanks for the feedback!
Having an infinite window by default will definitely lead to memory consumption and slow does in graph performance.
I’ll try to push a new round of updates in the next few days and will include your proposal.

I’ll probably go with a 15s window by default. It is small enough to not cause issues even on (relatively) massive data amounts, relatively long to see variations on charts in many applications, and relatively rapid to reach to quickly see that there is a window applied on the data (and trigger a search for the setting just above)

**Comment by IamPhytan** [comment]
Looking forward for the next update ! Can't wait for the features that will be embedded in it

**Comment by nesnes** [comment]
The version 1.0.8 has been released and fixes the duration of the window the 15s along with other sneaky features here and  there ;)
