### ISSUE TITLE
WSL2 launch error

### ISSUE THREAD

**Issue by bartmeuris** [nesnes/teleplot-vscode#3]
I was testing out teleplot on VSCode on native windows with platformio, which looked extremely nice, but now also wanted to use it in a project running in a WSL2 "subsystem for linux" Ubuntu-20.04 environment.

The extension successfully installed (or so it seemed) in the WSL environment (this needs to be installed separately), however the status bar icon does not appear, and when I try to launch it through the command menu with the `teleplot: Start teleplot session`, I get the following error:

> Command 'teleplot: Start teleplot session' resulted in an error (command 'teleplot.start' not found)

More info on VSCode + WSL (and support for remote support in extensions):

* https://code.visualstudio.com/docs/remote/wsl
* https://code.visualstudio.com/api/advanced-topics/remote-extensions

**Comment by 80avin** [comment]
I guess this is because USB devices are not supported in WSL2.
Reference: https://github.com/microsoft/WSL/issues/4322

**Comment by luzz94** [comment]
Unfortunately seems not working also in a standard partition of Ubuntu 20.04, i've the same problem.

**Comment by nesnes** [comment]
I didn’t yet tried to execute the extension from a WSL environment in windows, however there was a lot of issues in the past few month with VSCode and dependencies updates.
By the way, if you are not using the serial ports but just the UDP “protocol”, Teleplot is also available in its own repo, as a local web server, out of VSCode. https://github.com/nesnes/teleplot

Can I have details on your use case?
