### ISSUE TITLE
Extension is Broken on VS Code 1.66

### ISSUE THREAD

**Issue by Coriago** [nesnes/teleplot-vscode#4]
I tried to use the extension on the latest version of vs code, 1.66 March 2022 update. The extension button does not show up in the lower left hand corner and trying to run `teleplot: Start teleplot session` gives an error saying `teleplot.start` is not a valid command. I reverted VS Code back to 1.64 January 2022 and the button appeared and the extension worked.

**Comment by nesnes** [comment]
There were some issue with a VS ode update indeed, can you test the latest 1.0.7 version of the extension ?
