### ISSUE TITLE
Extansion broken ?

### ISSUE THREAD

**Issue by CorentinPacaud** [nesnes/teleplot-vscode#5]
I tried the example you give, but nothing happened. I verified the com port and baud rate.
It's blocked on this page. "Refresh" and "open" don't do anything.
VSCODE VERSION : 
Version: 1.67.2 (user setup)
Commit: c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5
Date: 2022-05-17T18:15:52.058Z
Electron: 17.4.1
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Windows_NT x64 10.0.19044

![image](https://user-images.githubusercontent.com/10416367/172425221-71cfadeb-2afb-4c0a-aa60-62c18b3351eb.png)

**Comment by iotregenesis** [comment]
Same goes to my vscode setup on MXLinux (based on Debian 11 Bullseye)

Teleplot V1.0.6 is not working as described in issue #5 above (https://github.com/nesnes/teleplot-vscode/issues/5#issue-1263512936)

VSCode Version on Linux
================
Version: 1.67.2
Commit: c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5
Date: 2022-05-17T18:23:40.286Z
Electron: 17.4.1
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Linux x64 5.14.0-4mx-amd64

**Comment by nesnes** [comment]
Can you try the latest 1.0.7 version of the extension? 
I was able to reproduce and fix the issue but I want to make sure it also works in your side.
