### ISSUE TITLE
Not an issue, Just compliment!

### ISSUE THREAD

**Issue by OptifySudarshanPatil** [nesnes/teleplot-vscode#7]
Hello @nesnes ,
This is fantastic tool.

**Comment by nesnes** [comment]
Thank you very much! This is the kind of message that’s very much appreciated!
Don’t hesitate to share about Teleplot around you so it can help more people ;)

(and you remind me that I have to update the VSCode extension, it is a bit behind the standalone version at teleplot.fr and misses a few features like units, text-based telemetry and 3D objects)

**Comment by OptifySudarshanPatil** [comment]
> Thank you very much! This is the kind of message that’s very much appreciated! Don’t hesitate to share about Teleplot around you so it can help more people ;)
> 
> (and you remind me that I have to update the VSCode extension, it is a bit behind the standalone version at teleplot.fr and misses a few features like units, text-based telemetry and 3D objects)



> Don’t hesitate to share about Teleplot around you so it can help more people ;)

Definitely!
